name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest  # For linting and testing

      - name: Lint code
        run: flake8 src/

      - name: Run tests
        run: pytest tests/  # Adjust if you have tests

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t yourdockerhubusername/housing-api:latest .

      - name: Push Docker image
        run: docker push yourdockerhubusername/housing-api:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment script
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
